//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPPLIERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_CONTRACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERY_CONTRACT()
        {
            this.PURCHASE_INVOICE = new HashSet<PURCHASE_INVOICE>();
            this.TAG_DELIVERY_CONTRACT = new HashSet<TAG_DELIVERY_CONTRACT>();
        }
    
        public int DELIVERY_CONTRACT_ID { get; set; }
        public string NUMBER { get; set; }
        public int FK_SUPPLIER_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime DATE_FINISH { get; set; }
        public string COMMENT { get; set; }
        public int FK_USER_ID_CREATOR { get; set; }
        public System.DateTime DATE_CREATION { get; set; }
        public Nullable<int> FK_USER_ID_CHANGED { get; set; }
        public Nullable<System.DateTime> DATE_CHANGE { get; set; }
    
        public virtual SUPPLIER SUPPLIER { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE_INVOICE> PURCHASE_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG_DELIVERY_CONTRACT> TAG_DELIVERY_CONTRACT { get; set; }
    }
}
