//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPPLIERS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMBIT : DbContext
    {
        public AMBIT()
            : base("name=AMBIT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DELIVERY_CONTRACT> DELIVERY_CONTRACT { get; set; }
        public virtual DbSet<EMAIL> EMAIL { get; set; }
        public virtual DbSet<OPENING_HOURS> OPENING_HOURS { get; set; }
        public virtual DbSet<PHONE> PHONE { get; set; }
        public virtual DbSet<PHONE_FORMAT> PHONE_FORMAT { get; set; }
        public virtual DbSet<PROFILE> PROFILE { get; set; }
        public virtual DbSet<PURCHASE_INVOICE> PURCHASE_INVOICE { get; set; }
        public virtual DbSet<QUALITY> QUALITY { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIER { get; set; }
        public virtual DbSet<TAG> TAG { get; set; }
        public virtual DbSet<TAG_DELIVERY_CONTRACT> TAG_DELIVERY_CONTRACT { get; set; }
        public virtual DbSet<TAG_PURCHASE_INVOICE> TAG_PURCHASE_INVOICE { get; set; }
        public virtual DbSet<TAG_SUPPLIER> TAG_SUPPLIER { get; set; }
        public virtual DbSet<TIME_ZONE> TIME_ZONE { get; set; }
        public virtual DbSet<TYPE_ACTIVITY> TYPE_ACTIVITY { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
