//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPPLIERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPENING_HOURS
    {
        public int OPENING_HOURS_ID { get; set; }
        public int FK_SUPPLIER_ID { get; set; }
        public int DAY { get; set; }
        public Nullable<System.TimeSpan> START { get; set; }
        public Nullable<System.TimeSpan> END { get; set; }
    
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
