//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPPLIERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONE
    {
        public int PHONE_ID { get; set; }
        public int FK_SUPPLIER_ID { get; set; }
        public int FK_PHONE_FORMAT_ID { get; set; }
        public string NUMBER { get; set; }
        public string COMMENT { get; set; }
    
        public virtual PHONE_FORMAT PHONE_FORMAT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
