//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPPLIERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONE_FORMAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONE_FORMAT()
        {
            this.PHONE = new HashSet<PHONE>();
        }
    
        public int PHONE_FORMAT_ID { get; set; }
        public string FORMAT { get; set; }
        public string FLAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONE> PHONE { get; set; }
    }
}
