//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPPLIERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASE_INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PURCHASE_INVOICE()
        {
            this.TAG_PURCHASE_INVOICE = new HashSet<TAG_PURCHASE_INVOICE>();
        }
    
        public int PURCHASE_INVOICE_ID { get; set; }
        public string NUMBER { get; set; }
        public int FK_DELIVERY_CONTRACT_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public int FK_QUALITY_ID { get; set; }
        public int FK_STATUS_ID { get; set; }
        public string COMMENT { get; set; }
        public int FK_USER_ID_CREATOR { get; set; }
        public System.DateTime DATE_CREATION { get; set; }
        public Nullable<int> FK_USER_ID_CHANGED { get; set; }
        public Nullable<System.DateTime> DATE_CHANGE { get; set; }
    
        public virtual DELIVERY_CONTRACT DELIVERY_CONTRACT { get; set; }
        public virtual QUALITY QUALITY { get; set; }
        public virtual STATUS STATUS { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG_PURCHASE_INVOICE> TAG_PURCHASE_INVOICE { get; set; }
    }
}
