//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPPLIERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPPLIER()
        {
            this.DELIVERY_CONTRACT = new HashSet<DELIVERY_CONTRACT>();
            this.EMAIL = new HashSet<EMAIL>();
            this.OPENING_HOURS = new HashSet<OPENING_HOURS>();
            this.PHONE = new HashSet<PHONE>();
            this.TAG_SUPPLIER = new HashSet<TAG_SUPPLIER>();
        }
    
        public int SUPPLIER_ID { get; set; }
        public string NAME { get; set; }
        public int FK_TIME_ZONE_ID { get; set; }
        public string INN { get; set; }
        public bool FORM_OWNERSHIP { get; set; }
        public int FK_TYPE_ACTIVITY_ID { get; set; }
        public int FK_PROFILE_ID { get; set; }
        public string ADDRESS { get; set; }
        public int FK_USER_ID_CREATOR { get; set; }
        public System.DateTime DATE_CREATION { get; set; }
        public Nullable<int> FK_USER_ID_CHANGED { get; set; }
        public Nullable<System.DateTime> DATE_CHANGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY_CONTRACT> DELIVERY_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAIL> EMAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPENING_HOURS> OPENING_HOURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONE> PHONE { get; set; }
        public virtual PROFILE PROFILE { get; set; }
        public virtual TIME_ZONE TIME_ZONE { get; set; }
        public virtual TYPE_ACTIVITY TYPE_ACTIVITY { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG_SUPPLIER> TAG_SUPPLIER { get; set; }
    }
}
