//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPPLIERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAG()
        {
            this.TAG_DELIVERY_CONTRACT = new HashSet<TAG_DELIVERY_CONTRACT>();
            this.TAG_PURCHASE_INVOICE = new HashSet<TAG_PURCHASE_INVOICE>();
            this.TAG_SUPPLIER = new HashSet<TAG_SUPPLIER>();
        }
    
        public int TAG_ID { get; set; }
        public string NAME { get; set; }
        public string COLOR { get; set; }
        public string DESCRIPTION { get; set; }
        public int FK_USER_ID_CREATOR { get; set; }
        public System.DateTime DATE_CREATION { get; set; }
        public Nullable<int> FK_USER_ID_CHANGED { get; set; }
        public Nullable<System.DateTime> DATE_CHANGE { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG_DELIVERY_CONTRACT> TAG_DELIVERY_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG_PURCHASE_INVOICE> TAG_PURCHASE_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG_SUPPLIER> TAG_SUPPLIER { get; set; }
    }
}
