//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPPLIERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAG_PURCHASE_INVOICE
    {
        public int TAG_PURCHASE_INVOICE_ID { get; set; }
        public int FK_PURCHASE_INVOICE_ID { get; set; }
        public int FK_TAG_ID { get; set; }
    
        public virtual PURCHASE_INVOICE PURCHASE_INVOICE { get; set; }
        public virtual TAG TAG { get; set; }
    }
}
