//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPPLIERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.DELIVERY_CONTRACT = new HashSet<DELIVERY_CONTRACT>();
            this.DELIVERY_CONTRACT1 = new HashSet<DELIVERY_CONTRACT>();
            this.PURCHASE_INVOICE = new HashSet<PURCHASE_INVOICE>();
            this.PURCHASE_INVOICE1 = new HashSet<PURCHASE_INVOICE>();
            this.SUPPLIER = new HashSet<SUPPLIER>();
            this.SUPPLIER1 = new HashSet<SUPPLIER>();
            this.TAG = new HashSet<TAG>();
            this.TAG1 = new HashSet<TAG>();
        }
    
        public int USER_ID { get; set; }
        public string FIO { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public int FK_ROLE_ID { get; set; }
        public Nullable<System.DateTime> LAST_ACTIVITY { get; set; }
        public bool STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY_CONTRACT> DELIVERY_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY_CONTRACT> DELIVERY_CONTRACT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE_INVOICE> PURCHASE_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE_INVOICE> PURCHASE_INVOICE1 { get; set; }
        public virtual ROLE ROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER> SUPPLIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER> SUPPLIER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG> TAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG> TAG1 { get; set; }
    }
}
